### ISSUE TITLE
Make applicatation easily runnable

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#125]
Currently I don't know how to launch the examples.
I think the applications should be easily testable and run-able using `bailador` and deploy-able using `crust`. I don't think there is a need to be able to run them using plain `perl6`.
So IMHO `baile()` is either not needed or should not launch a web server by itself.

**Comment by ufobat** [comment]
We talked about this issue a bit in the slack channel. I think there are two "standards" we could use for the file that contains the web application. 

**p6w**
The first way would be a P6W app, probably best with the file extention *.p6w. This file can be used to in combination with crust, because crust is the tool of choice to work with p6w apps. If one chooses this aproach he has 
* all the benefits of p6w, e.g using P6W Middlewars, different servers, etc.
* an app that can easily be tested 

**perl6**
Second, it is still possible to use `baile()` in the file. This makes the whole thing a perl6 script. so there are no P6W advantages. Still there are other advantages:
* There are no dependencies on crust in order to run the script.
* invokable with perl6 itself. ( I still fiddle around with the binaries installed by zef because I dont have them in my $PATH by default. for someone who doesn't know much P6W nor crust it is the most **obvious** thing to start a perl6 programm with perl6 )
* Configuration Settings regarding host and port can go into effect. ( there is no way to ask a P6W app for its favorite host/port)
* We could define on which p6w server we run ( There are a few and bailador is just working on one. which is hopfully not "bailadors fault". still, it is just tested with one. Later, when we want to swich the default server for a Multithreaded/Async one it could be easily propagated because everone useing `baile()` would automatically switch )

I would not invent a new format. For example with returning the Bailador::App, because
* we would still have a file what can't be invoked with perl6 directly. 
* we would need to write a lot of code that is probably pretty much included in crust. and we would reinvent all the bugs. ;-)

**Comment by szabgab** [comment]
I don't think I understand. 

As it is right now, returning `app.get-psgi-app`
 * During development: , we can use (re)bailador. We don't have a dependency on `crust`.
 * Testing: we can test as we do it for the examples
 * Production: we can use `crust` or something similar that will come in the future

I don't understand: is there no way to tell crust which port and host we would like to use?

Running with perl6: I don't think it is really necessary, but maybe if people used `baile()` and what we had in Bailador is 

```
sub baile() {
   return app.get-psgi-app;
}
```
then that baile() function could check if we are being executed directly as a perl6 script and either exit with an explanation how to run the app, or would actually run the same thing (re)bailador runs.

**Comment by ufobat** [comment]
I try to explain it better now, hope this understandable.

> 
> As it is right now, returning app.get-psgi-app
> 
> * During development: , we can use (re)bailador. We don't have a dependency on crust.

No. I dont think that would actually work nicely. Thats bug is a result of doing so #130. I woud *not* do this *at all*, because:

If we return a P6W app like we currently do with `app.get-psgi-app` we would currently need `crustup` (the perl6 counterpart to plackup) to run/invoke this app within a P6W-HTTP-Server.

If I understood you correclty that we would further want the `bailador` programm to be able to run this P6W app within a P6W-HTTP-Server as well, we would actually need to do *exactly the same* job as crustup does. I would say that doing this would be reinventing the wheel. We would build a tool that would be able to run any p6w App on top of any (or maybe even just our) P6W HTTP Server. There would be new bugs while there are no benefits form it and there is nothing wrong with `crustup`

(Just as a note. Zoffix Bailador restarter plugin worked nicely because he used baile() to *start* the app and ivoked a new perl6 programm. )

> 
> I don't understand: is there no way to tell crust which port and host we would like to use?

I think you mean from inside bailador to crustup, like from Bailador::Configuration to Crust::Runner. No there is no way of doing that. This is not part of P6W. P6W is specifying the *communication* between Web App and HTTP Server. If you want to apply this settings you need to do it manually.

`crustup --server HTTP::Easy::PSGI --port 9090 --host 127.0.0.1 test.p6w`

We are currently just wanting a feature that "restarts" the Web Application. I'd hope to introduce this feature into crustup, I think this is the right place for it.

> 
> I don't understand: is there no way to tell crust which port and host we would like to use?

I think you mean from inside bailador to crustup, like from Bailador::Configuration to Crust::Runner. *No*, there is no way of doing that. If you want to apply this settings you need to do it manually.

i'd like to have this possible:

`crustup --server HTTP::Easy::PSGI --port 9090 --host 127.0.0.1 --watch "lib,whatever,..." test.p6sgi`

On the other hand if someone uses `baile()` in order to start the Web Application we can still have influence in host, port and P6W HTTP Server. I think we should not throw this feature away because people are used to have it. It is in Bailador ever since, and there are counterparts in Dancer and Mojo as well.

Regarding your suggestion to return the P6W app from `baile()`. I think that is quite good. It looks far better as doing this ugly `app.to-psgi-app()` we should use a parameter for this. Mojo does something similar

http://mojolicious.org/perldoc/Mojolicious#start

so we would have subs like this:
```perl6
sub baile("p6w") # returns a p6w app
sub baile("start", "host", 3000") # starts it directly
... # with the different variations we already have
```

**Comment by szabgab** [comment]
So if I understand you correctly we would not be able to run a bailador app on its own (not even for development), we would need crust for that, right?

As far as I know Flask comes with a tool called flask that can run a flask-based app. It is used during development, but not suggested for production.  (I think morbo is the same for Mojolicious)

**Comment by ufobat** [comment]
Mojo has done a lot of awesome work with its Mojolicious::Commands.
https://metacpan.org/pod/Mojolicious::Commands#SYNOPSIS

When one invokes a mojo app it passes parameters to the Mojolicious::Commands, those commands are for example "psgi", "deamon", "hypnotoad", "morbo" or similar stuff. Mojo even guesses its environment to automatically try to behave correctly == call the correct command.

I wasn't aware if or how Dancer2 does this. So i just read the source code. This is what I've found:
https://metacpan.org/source/CROMEDOME/Dancer2-0.205000/lib/Dancer2/Core/Runner.pm

Bailador is not yet having similar things :-(
I *now* ( Thanks to Gabor!! ) understand this ticket as a Feature Request in order to introduce such a Command and Guessing Layer into Bailador.

The ugly hack as described in #130 should not be continued!

The guessing layer tries to figure out if a script/app were invoked in a P6W context or in a perl6 context.

Right now, without guessing layer, we have to define/state it +explicitly*. This means if your script returns a P6W app `app.to-psgi-app()` you need to use crustup if you dont return a P6W app you need to start it with `baile()`.

**Comment by ufobat** [comment]
There are Bailador::Comannds that can be used now, so the general thing is fine. Those commands should be included in bin/bailador, which is some detail work. i'd considder this ticket as closed
