### ISSUE TITLE
Should config.views really be relative to $*CWD ?

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#169]
By default config.views has 'views' which means it is relative to current working directory when the app was launched.
Shouldn't views be relative to the app.pl file in the normal case as well?

Should't config.views contain an absolute path?

**Comment by ufobat** [comment]
I agree with you.
this applies to template and other similar settings. we should check that as well.

**Comment by ufobat** [comment]
See #174.

I think the directories should be relative to Bailador::App $.location. 
If the paths in different member variables of Bailador::Configuration are absolute it should work as well.

**Comment by szabgab** [comment]
I see `$.location` is the root directory. Relative to that sounds fine. The questions, how to determine the that? What I tried in lib/Bailador/Configuration.pm was to provide a solution for both when the `app.pl6` is in the root directory of the project and when it is inside the `bin` directory.

**Comment by ufobat** [comment]
My ideas for all the issues are those:

* We should remove Bailador::import() because it does nothing we do not already know. $*PROGRAM.parent() is the directory in which the app is located. If you can't call import() anymore it wont mess anything up when you call it, or when you forget to call it. That is basically #174.

* There are some places when we use $.location (which lies in Bailador::App) and some places when this is not available, for example in routes where I used $*PROGRAM.parent directly. I'd like to unify this as well. This value 
    - should get initialized in `baile()`, because just before we start serving web requests. that would be the right place to make final adaptions. (For example what Bailador::Feature::AutoHead does or Ticket #143 - where we should ensure the the configuration is read only).
    - should be accessable whereever it is needed
    - and it should be read only from this point on. (You should not be able to change this in the Routes-Code) 
(Maybe) The (readonly, again see #143) Bailador::Configuration object should be accessable in any place! I dont have a solution for this so far ;-( I would gladly hear your suggestions.

* But, how should the former $.location be obtained?

Gabor implemented a "magic" that checkes wether the app is in a directory called "bin", if so we take the parent of "bin" to be the $.location. That is often what you want but sometimes you might want to state the app root. So how else could we influcence this:
    - IMHO %*ENV<BAILADOR_APP_ROOT> makes sense,
    - or stating it in the app itself:

```perl6
use Bailador;

config.app-root = '/opt/myapp/'.IO;

get '/' => sub { "Hi!" };

```

    - it makes no sense to state it in the configuration files, because the configuration files depend on knowing the app-root first!
    
So if there is not stating of the app-root location Gabors magic will happen.

**Comment by ufobat** [comment]
this would fix #189 as well :)

**Comment by szabgab** [comment]
Sound good to me though I don't know if we really need the env variable. At least I can't see the need *yet*.

What about having a separate module (e.g. Bailador::Tools) that has a function called get_root() that will be able to calculate and return the root of the current app?

And one thing, that I have not tried yet as I have not tried real deployment yet: What if we are launching several unrelated applications? Will this implementation be a problem for that scenario?

**Comment by ufobat** [comment]
The helper in Bailador::Tools is added.

**Comment by ufobat** [comment]
> should get initialized in baile(), because just before we start serving web requests. that would be the right place to make final adaptions. (For example what Bailador::Feature::AutoHead does or Ticket #143 - where we should ensure the the configuration is read only).

that is actually wrong. it needs to be initialized before `baile()`. there is a 'before-add-routes() which will be called right after the $!location is used for the first time/determined. There is a case that you dont need to the $location anywere, so `baile()` calles it as a last resort.
