### ISSUE TITLE
How to reuse routes in another application?

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#237]
See the `examples/reuse` directory and the `t/30-examples-reuse*` tests added in 7765bf8b98a404f0a2189d0ed51490e9c90094be for an experiment.

**Comment by ufobat** [comment]
I think this is actually no longer required. in the last view commits i've added support for controler classes. Since controler classes are regular perl6 classed which can be extended, there is no need to create different subclasses of Bailador::App.

Imho Subclassing Bailador::App makes sense only if this subclass changes / influences the behaviour of Bailador::App itself. we're subclassing as a workaround for not having controllers.
