### ISSUE TITLE
is bailador still being developed

### ISSUE THREAD

**Issue by wtwt5237** [Bailador/Bailador#315]
Dear ufobat

Is bailador still being actively developed? I am learning raku, and find bailador to be great for web development. I would really love to learn it, but it seems like there are not too many developments in recent months. Want to know what your plan is for this package?

Thanks!

Tao

**Comment by ufobat** [comment]
Hello Tao,

currently it isnt actively developed. Of course you could still use Bailador and if you find bugs I would try to do my best in order to fix them.
Bailador does not Support HTTP/2 and depends on P6W (= which is the raku version of perl5's PSGI ) which is not really popular.

Have a look at Cro! :)
