### ISSUE TITLE
Document an example of how to start up a class-based app

### ISSUE THREAD

**Issue by zoffixznet** [Bailador/Bailador#78]
The docs on the [class-based interface](https://github.com/zoffixznet/Bailador/blob/b564be5615a63f3993b6619064adaf5a807a1bad/README.md#web-applications-via-inheriting-from-bailadorapp) don't say anything about how to start a class-based app.

I tried copying the sub app code and launching with this:

``` perl6
given HTTP::Easy::PSGI.new(:host<0.0.0.0>, :3000port) {
    .app(Party.new.get-psgi-app);
    say "Entering the development dance floor: http://0.0.0.0:3000";
    .run;
}
```

EDIT: the below was a different issue and no longer applies. This Issue is only about docs now.
~~And the app starts, but none of the attributes seem to be in it, such as:~~

``` perl6
        self.location = '.';
        self.renderer = Bailador::Template::Mojo::Extended.new;
```

**Comment by ufobat** [comment]
You're right, the documentation is not covering it. It is on my todo list. I didn't add this section because bailador is not at dancing on other http/psgi servers, because everyone has a different psgi/p6sg/p6w implementation.

I've added the `get-psgi-app` method because this would allow to use different methods to start the app. For Example:
  * [crustup](https://github.com/tokuhirom/p6-Crust/blob/master/bin/crustup)

    which behaves like [plackup](http://search.cpan.org/~miyagawa/Plack-1.0039/script/plackup)

  * `app` 

    https://github.com/ufobat/Bailador/blob/master/lib/Bailador.pm#L15
    which i am using in my [playground](https://github.com/ufobat/VoteImproved/blob/master/bin/VoteImproved.p6)

**Comment by ufobat** [comment]
how do you know that the attributes are not in it? because it isn't working as expected?

using relative paths like `.` relay on that you start the process always from the same working directory. 

In my [Playground](https://github.com/ufobat/VoteImproved/blob/master/lib/VoteImproved.pm6#L22) i am doing it like that.... but since it containts the "views" directory already, I am wondering why this works.. https://github.com/ufobat/Bailador/blob/master/lib/Bailador/App.pm#L21

I will have a look on that.

**Comment by zoffixznet** [comment]
> how do you know that the attributes are not in it? because it isn't working as expected?

Yeah, I have [this code](https://github.com/zoffixznet/perl6.party/blob/class/bin/app.p6#L22) and if I remove `app.location: '.'` before my class, it fails to find the `views/` directory. But with it, it complains about an error in my templates, because it's using the `::Mojo` template renderer and not the `::Extended` renderer I assign in `self.renderer`

**Comment by ufobat** [comment]
your code seems to work here :-(

https://gist.github.com/ufobat/bb86690139a7133171092dc41aa4396b

```
% perl6 test.pl6      
.
Bailador::Template::Mojo::Extended.new
Entering the development dance floor: http://0.0.0.0:3000
[2016-05-06T18:59:18Z] Started HTTP server.
^C
```

**Comment by zoffixznet** [comment]
Actually that code doesn't work. If you try to render anything it'll still use the default location/template renderer.

BUT, I found the issue. It's the left-over `use Bailador` statement. I guess it sets up the default app and my custom app with its custom setting never gets a chance to live. Commenting out use Bailador works.

**Comment by ufobat** [comment]
it is documented in Mixing both Approaches
so i'd considder this as closed
