### ISSUE TITLE
missing head route?

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#98]
When I try the basic example in the README and then run ```curl -I http://localhost:3000/``` I get 
```
HTTP/1.1 404 Not Found
Content-Type: text/html, charset=utf-8
```
instead of the header. I wonder if defining any route should also create a 'head' route
and/or one should be able to create a head route separately?

**Comment by ufobat** [comment]
Well, at least you should be able to create a head route.

**Comment by szabgab** [comment]
Is it possible? I could not find how to do that.

**Comment by ufobat** [comment]
it would be possible via 
https://github.com/ufobat/Bailador/blob/master/lib/Bailador/Route.pm#L127  https://github.com/ufobat/Bailador/blob/master/lib/Bailador.pm#L11) .

Something like this should work. 
``` app().add_route('HEAD' => sub {]); ```

but there is no (not yet?) syntactical suggar for it:

https://github.com/ufobat/Bailador/blob/master/lib/Bailador/Route.pm#L133
https://github.com/ufobat/Bailador/blob/master/lib/Bailador.pm#L24

it should be just a small change, I think.

**Comment by szabgab** [comment]
Still an open question: What should happen if there is only POST defined for a route and someone asks for HEAD ?

**Comment by ufobat** [comment]
I think this implementation is a bit problematic, because

1) it is "magic" so i would rather have this implemented in a Bailador::Feature, maybe? I thought thats a good place to put special behaviour implementations, maybe the gradual fits in a feature as well?. but thats just an idea

2) the code only does not render the body if you use the auto-render mechanism, if you call self.render() in your code of the route the body would probably printed as well

3) the whole code would be calculated, for example get is something that's starts a mp3 stream. noone would ever consume it and it might not get terminated and delivered and maybe in memory for ever

so my suggestions are:

`Bailador::Feature::AutoHead` which,
* generates a HEAD route for each GET route, unless you specified one manually
* changes the behavour of `render()` for auto generated head routes because, it must omit the body (also if you call render() manually.
